### ISSUE TITLE
How do I install Atlantis and partyMod?

### ISSUE THREAD

**Issue by kgweiss** [cancerdatasci/atlantis#2]
Greetings,

I have tried multiple approaches to install atlantis on my Linux system with R/3.6.0

Using:

devtools::install_github("cancerdatasci/atlantis")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`cancerdatasci`) and repo name (`atlantis`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

I am able to clone the repo but R CMD INSTALL partyMod -l ./tRpkg

complains with this message:  Error: classes "ExpectCovar", "ExpectCovarInfluence" are not exported by 'namespace:coin'

I have installed the prerequisites that I could find by scouring the code.

A detailed installation procedure would be most helpful.

Thanks,
Ken

**Comment by kgweiss** [comment]
Just tried the following with the results shown:

> devtools::install_github("cancerdatasci/atlantis")
Downloading GitHub repo cancerdatasci/atlantis@HEAD
Error: Failed to install 'atlantis' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)

Weird. 

Thanks,
Ken

**Comment by yesitsjess** [comment]
I'd also like to know this. I tried install_github and got the same error as Ken. I tried cloning the git repo and running install_local but I get `Error: Could not find tools necessary to compile a package`. 

I then tried to source each R script from the package like so:
`library(party)`
`for(x in dir("atlantis/partyMod/R/")) source(paste0("atlantis/partyMod/R/", x))`
`for(x in dir("atlantis/atlantis/R/")) source(paste0("atlantis/atlantis/R/", x))`

but when I try to source the atlantis folder I get:
`Error in loadNamespace(name) : `
`  there is no package called ‘atlantisPartyMod'`

**Comment by yesitsjess** [comment]
Ah, try devtools::install_github("cancerdatasci/atlantis/partyMod")
You might need https://cran.r-project.org/bin/windows/Rtools/ if you're using windows
I'm currently getting an error from the coin package but I expect this will be solved by using an older version e.g. v1.2-2

edit - yes, I can confirm this method works for me

**Comment by kgweiss** [comment]
Greetings,

Thank you so much for getting back to me. I tried the devtools::install_github approach and received the following (using R/3.6.0):

> devtools::install_github("cancerdatasci/atlantis/partyMod")
Downloading GitHub repo cancerdatasci/atlantis@master
Installing 10 packages: zoo, sandwich, strucchange, modeltools, coin, libcoin, matrixStats, mvtnorm, multcomp, TH.data

… (messages from all the other packages installed). They all installed cleanly, with assorted warnings, until ….

** byte-compile and prepare package for lazy loading
Error: classes "ExpectCovar", "ExpectCovarInfluence" are not exported by 'namespace:coin'
Execution halted
ERROR: lazy loading failed for package ‘atlantisPartyMod’
* removing ‘/home/kgweiss/R/x86_64-pc-linux-gnu-library/3.6/atlantisPartyMod’
Error: Failed to install 'atlantisPartyMod' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpqv20D7/file637001c421c9d/atlantisPartyMod_1.0.16.1.tar.gz’ had non-zero exit status


This error is what I was getting previously with the PartyMod installation.



Tried using coin 1.2-2, which installed fine. Then tried installing PartyMod again and got:

Error: classes "ExpectCovar", "ExpectCovarInfluence" are not exported by 'namespace:coin'
Execution halted
ERROR: lazy loading failed for package ‘atlantisPartyMod’
* removing ‘/home/kgweiss/R/x86_64-pc-linux-gnu-library/3.6/atlantisPartyMod’
Error: Failed to install 'atlantisPartyMod' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpqv20D7/file6370053ca6149/atlantisPartyMod_1.0.16.1.tar.gz’ had non-zero exit status

Please advise.

Thanks,
Ken

**Comment by yesitsjess** [comment]
Confirm you're definitely using coin v1.2-2 or older. I think you have a newer version sourced still. By the way, I'm just another user, I'm by no means an expert.

**Comment by kgweiss** [comment]
Jess,

I’ll keep trying. I VERY much appreciate your willingness to share anything that may help.

Cheers,
Ken

**Comment by kgweiss** [comment]
Greeings,

With Jess' help (HUGE thank you), I was able to develop the following recipe to install atlantisPartyMod successfully.


`mkdir -p ~/R/x86_64-pc-linux-gnu-library/3.6    ---You can skip this step if the directory already exists`
`export R_LIBS_USER=~/R/x86_64-pc-linux-gnu-library/3.6`
`R`

>     install.packages("devtools", lib="~/R/x86_64-pc-linux-gnu-library/3.6")
>     install.packages("coin",lib="~/R/x86_64-pc-linux-gnu-library/3.6", dependencies=TRUE)
>     remove.packages("coin",lib="~/R/x86_64-pc-linux-gnu-library/3.6")
>     q()
>     n
`wget https://cran.r-project.org/src/contrib/Archive/coin/coin_1.2-2.tar.gz`
`R CMD INSTALL coin_1.2-2.tar.gz lib="~/R/x86_64-pc-linux-gnu-library/3.6"`
`R`
>     devtools::install_github("cancerdatasci/atlantis/partyMod",lib="~/R/x86_64-pc-linux-gnu-library/3.6")
>     Enter one or more numbers, or an empty line to skip updates:   ---press enter to skip the updates
>     library("atlantisPartyMod")

Cheers,
Ken

**Comment by kgweiss** [comment]
One more piece left to do. the actual install of atlantis. Here is what I did:

`cd ~`
` git clone https://github.com/cancerdatasci/atlantis.git`
`export R_LIBS_USER=~/R/x86_64-pc-linux-gnu-library/3.6   ---no need to do this again if you set R_LIBS_USER in previous post`
`R`
` install.packages("AUC",lib="~/R/x86_64-pc-linux-gnu-library/3.6")`
` install.packages("foreach",lib="~/R/x86_64-pc-linux-gnu-library/3.6",dependencies=TRUE)`
`install.packages("iterators",lib="~/R/x86_64-pc-linux-gnu-library/3.6",dependencies=TRUE)`
` install.packages("caTools",lib="~/R/x86_64-pc-linux-gnu-library/3.6",dependencies=TRUE)`
`install.packages("bitops",lib="~/R/x86_64-pc-linux-gnu-library/3.6",dependencies=TRUE)`
`q()`
`n`
` R CMD INSTALL atlantis -l $R_LIBS_USER`
`R`
`library("atlantis")`

Closing this issue.

Cheers,
Ken
